from app.domain.errors.exceptions import (
    DomainError,
    EmailNotVerifiedError,
    InactiveUserError,
    InvalidEmailError,
    InvalidFirebaseUidError,
    InvalidNationalityError,
    InvalidObservedAtError,
    InvalidReportCategoryError,
    InvalidReportDescriptionError,
    InvalidReportPositionError,
    InvalidUsernameError,
    ReportClientIdConflictError,
    ReportNotFoundError,
    UserAlreadyExistsError,
    UserNotFoundError,
    UsernameAlreadyExistsError,
)
